// Generated by BUCKLESCRIPT VERSION 1.5.3+dev, PLEASE EDIT WITH CARE
'use strict';


var triangles = 4;

var triangle_strip = 5;

var texture0 = 33984;

var texture1 = 33985;

var texture2 = 33986;

var texture_2d = 3553;

var blend = 3042;

var texture_wrap_s = 10242;

var texture_wrap_t = 10243;

var clamp_to_edge = 33071;

var src_alpha = 770;

var one_minus_src_alpha = 771;

var dst_alpha = 772;

var depth_test = 2929;

var rgb = 6407;

var rgba = 6408;

var triangle_fan = 6;

var array_buffer = 34962;

var element_array_buffer = 34963;

var array_buffer_binding = 34964;

var element_array_buffer_binding = 34965;

var stream_draw = 35040;

var static_draw = 35044;

var dynamic_draw = 35048;

var buffer_size = 34660;

var buffer_usage = 34661;

var float_ = 5126;

var unsigned_int = 5125;

var current_vertex_attrib = 34342;

var fragment_shader = 35632;

var vertex_shader = 35633;

var max_vertex_attribs = 34921;

var max_vertex_uniform_vectors = 36347;

var max_varying_vectors = 36348;

var max_combined_texture_image_units = 35661;

var max_vertex_texture_image_units = 35660;

var max_texture_image_units = 34930;

var max_fragment_uniform_vectors = 36349;

var shader_type = 35663;

var delete_status = 35712;

var link_status = 35714;

var validate_status = 35715;

var attached_shaders = 35717;

var active_uniforms = 35718;

var active_attributes = 35721;

var shading_language_version = 35724;

var current_program = 35725;

var compile_status = 35713;

var vendor = 7936;

var renderer = 7937;

var version = 7938;

var float_vec2 = 35664;

var float_vec3 = 35665;

var float_vec4 = 35666;

var int_vec2 = 35667;

var int_vec3 = 35668;

var int_vec4 = 35669;

var bool_ = 35670;

var bool_vec2 = 35671;

var bool_vec3 = 35672;

var bool_vec4 = 35673;

var float_mat2 = 35674;

var float_mat3 = 35675;

var float_mat4 = 35676;

var sampler_2d = 35678;

var sampler_cube = 35680;

var unpack_flip_y_webgl = 37440;

var unpack_premultiply_alpha_webgl = 37441;

var context_lost_webgl = 37442;

var unpack_colorspace_conversion_webgl = 37443;

var browser_default_webgl = 37444;

var vertex_attrib_array_enabled = 34338;

var vertex_attrib_array_size = 34339;

var vertex_attrib_array_stride = 34340;

var vertex_attrib_array_type = 34341;

var vertex_attrib_array_normalized = 34922;

var vertex_attrib_array_pointer = 34373;

var vertex_attrib_array_buffer_binding = 34975;

var depth_buffer_bit = 256;

var stencil_buffer_bit = 1024;

var color_buffer_bit = 16384;

var unsigned_short = 5123;

var unsigned_byte = 5121;

var texture_mag_filter = 10240;

var texture_min_filter = 10241;

var linear = 9729;

var linear_mipmap_nearest = 9985;

exports.triangles                          = triangles;
exports.triangle_strip                     = triangle_strip;
exports.texture0                           = texture0;
exports.texture1                           = texture1;
exports.texture2                           = texture2;
exports.texture_2d                         = texture_2d;
exports.blend                              = blend;
exports.texture_wrap_s                     = texture_wrap_s;
exports.texture_wrap_t                     = texture_wrap_t;
exports.clamp_to_edge                      = clamp_to_edge;
exports.src_alpha                          = src_alpha;
exports.one_minus_src_alpha                = one_minus_src_alpha;
exports.dst_alpha                          = dst_alpha;
exports.depth_test                         = depth_test;
exports.rgb                                = rgb;
exports.rgba                               = rgba;
exports.triangle_fan                       = triangle_fan;
exports.array_buffer                       = array_buffer;
exports.element_array_buffer               = element_array_buffer;
exports.array_buffer_binding               = array_buffer_binding;
exports.element_array_buffer_binding       = element_array_buffer_binding;
exports.stream_draw                        = stream_draw;
exports.static_draw                        = static_draw;
exports.dynamic_draw                       = dynamic_draw;
exports.buffer_size                        = buffer_size;
exports.buffer_usage                       = buffer_usage;
exports.float_                             = float_;
exports.unsigned_int                       = unsigned_int;
exports.current_vertex_attrib              = current_vertex_attrib;
exports.fragment_shader                    = fragment_shader;
exports.vertex_shader                      = vertex_shader;
exports.max_vertex_attribs                 = max_vertex_attribs;
exports.max_vertex_uniform_vectors         = max_vertex_uniform_vectors;
exports.max_varying_vectors                = max_varying_vectors;
exports.max_combined_texture_image_units   = max_combined_texture_image_units;
exports.max_vertex_texture_image_units     = max_vertex_texture_image_units;
exports.max_texture_image_units            = max_texture_image_units;
exports.max_fragment_uniform_vectors       = max_fragment_uniform_vectors;
exports.shader_type                        = shader_type;
exports.delete_status                      = delete_status;
exports.link_status                        = link_status;
exports.validate_status                    = validate_status;
exports.attached_shaders                   = attached_shaders;
exports.active_uniforms                    = active_uniforms;
exports.active_attributes                  = active_attributes;
exports.shading_language_version           = shading_language_version;
exports.current_program                    = current_program;
exports.compile_status                     = compile_status;
exports.vendor                             = vendor;
exports.renderer                           = renderer;
exports.version                            = version;
exports.float_vec2                         = float_vec2;
exports.float_vec3                         = float_vec3;
exports.float_vec4                         = float_vec4;
exports.int_vec2                           = int_vec2;
exports.int_vec3                           = int_vec3;
exports.int_vec4                           = int_vec4;
exports.bool_                              = bool_;
exports.bool_vec2                          = bool_vec2;
exports.bool_vec3                          = bool_vec3;
exports.bool_vec4                          = bool_vec4;
exports.float_mat2                         = float_mat2;
exports.float_mat3                         = float_mat3;
exports.float_mat4                         = float_mat4;
exports.sampler_2d                         = sampler_2d;
exports.sampler_cube                       = sampler_cube;
exports.unpack_flip_y_webgl                = unpack_flip_y_webgl;
exports.unpack_premultiply_alpha_webgl     = unpack_premultiply_alpha_webgl;
exports.context_lost_webgl                 = context_lost_webgl;
exports.unpack_colorspace_conversion_webgl = unpack_colorspace_conversion_webgl;
exports.browser_default_webgl              = browser_default_webgl;
exports.vertex_attrib_array_enabled        = vertex_attrib_array_enabled;
exports.vertex_attrib_array_size           = vertex_attrib_array_size;
exports.vertex_attrib_array_stride         = vertex_attrib_array_stride;
exports.vertex_attrib_array_type           = vertex_attrib_array_type;
exports.vertex_attrib_array_normalized     = vertex_attrib_array_normalized;
exports.vertex_attrib_array_pointer        = vertex_attrib_array_pointer;
exports.vertex_attrib_array_buffer_binding = vertex_attrib_array_buffer_binding;
exports.depth_buffer_bit                   = depth_buffer_bit;
exports.stencil_buffer_bit                 = stencil_buffer_bit;
exports.color_buffer_bit                   = color_buffer_bit;
exports.unsigned_short                     = unsigned_short;
exports.unsigned_byte                      = unsigned_byte;
exports.texture_mag_filter                 = texture_mag_filter;
exports.texture_min_filter                 = texture_min_filter;
exports.linear                             = linear;
exports.linear_mipmap_nearest              = linear_mipmap_nearest;
/* No side effect */
